### ISSUE TITLE
The memory usage in LoRA finetuning

### ISSUE THREAD

**Issue by LaniakeaS** [RahulSChand/gpu_poor#5]
As far as i know, we can set lora rank and target module to change the number of trainable parameter, which, I think, can cause different memory usage. But i didn't fine any relevant setting in your project. How do you estimate memory usage without those information?

**Comment by RahulSChand** [comment]
Target module & rank cause very small changes in memory (therefore in the project, I assume target=[q,k] & rank=8). Most memory in LoRA finetuning is taken by model memory & activation memory (both which are independent of target & rank).

For example, Lets say you take llama-2-7b & finetune it using LoRA with two settings (for both seq_length = 500)
1. (target=[q], rank=4)
2. (target=[q,k,v] & rank=32) 

The extra memory due to change in target & rank will only be around ~100 MB. Since total memory during finetuning for these settings is around ~20GB. 100MB is only very small portion & can be safely ignored.
