### ISSUE TITLE
Name and size from same model can cause different result

### ISSUE THREAD

**Issue by LaniakeaS** [RahulSChand/gpu_poor#7]
For example, from model description on HuggingFaceH4/starchat-beta, the size of this is 16B. But I got different result with just setting "Name" to "starchat" than just setting "Size" to "16".

<img width="613" alt="image" src="https://github.com/RahulSChand/gpu_poor/assets/48688817/b1f4c83a-8448-4a25-a357-8061260b2dd1">
<img width="622" alt="image" src="https://github.com/RahulSChand/gpu_poor/assets/48688817/a93ec26e-e38b-4c09-ad75-38603692881a">

**Comment by RahulSChand** [comment]
Hi @LaniakeaS this happens because to calculate memory requirement, one needs `hidden_size`, `intermediate_size`, `num_layers`, `vocab_size` of the model (these are usually present in config.json & the app reads it from there)

But when you just input the size, the app has no idea about above values & has to "infer" them based on some assumptions. This part of the code, approximates the values of `hidden_size` etc. using just the final size (in billion) of the model

https://github.com/RahulSChand/gpu_poor/blob/a702c37a113baaaaa181bc5319255c9292f99240/src/App.js#L671-L705

This causes a difference, because given just the final size of the model it's impossible to say what EXACT hidden_size etc. they had

**Comment by LaniakeaS** [comment]
thank you for your answer!
